GET http://localhost:5294/api/User/GetUser
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjA4M2NlY2ZkLTM4N2QtNDQ1ZS04OWYyLWZmM2MwYmQ5NjNhNSIsImVtYWlsIjoiYWZrdXJ0a2FkaXJvZ2x1QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhaG1ldGFobWV0IiwianRpIjoiNjhjYzEzNjItOTFiNS00OTY0LTg5OTYtNDEwMDZiMDgyMjE3IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsImF1ZCI6WyJ3d3cuYXV0aHNlcnZlci5jb20iLCJ3d3cubWluaWFwaTEuY29tIiwid3d3Lm1pbmlhcGkyLmNvbSJdLCJuYmYiOjE3NTc0OTYyOTQsImV4cCI6MTc1NzQ5NjU5NCwiaXNzIjoid3d3LmF1dGhzZXJ2ZXIuY29tIn0.IMQD8Y48odhJivcGBhNf3gPCRcqkCGBJciqaVwuTsbM

### Token olustur
POST http://localhost:5294/api/Auth/CreateToken
Content-Type: application/json

{
  "email": "afkurtkadiroglu@gmail.com",
  "password": "YeniSifre123**"
}
### kullanıcı olustur
POST http://localhost:5294/api/User/CreateUser
Content-Type: application/json

{
  "userName": "ahmetfaruk",
  "email": "ahmet@mudbey.com.tr"
}
### Kaydı tamamlama (geçici şifre e-postadan gelir)
POST http://localhost:5294/api/User/CompleteRegistration
Content-Type: application/json

{
  "email": "ahmet@mudbey.com.tr",
  "temporaryPassword": "2xmR5yt&tG",
  "newPassword": "YeniSifre123**"
}
### Refresh ile token yenileme
POST http://localhost:5294/api/Auth/CreateTokenByRefreshToken
Content-Type: application/json

{
  "token" : "UouLQ0ApysuCUC3a2jHvETU3gJT5nPzDVlBweMrH/wg="
}
### Refresh Token geri alma (Yukarıdaki istekten dönen YENİ refresh token'ı kullan)
POST http://localhost:5294/api/Auth/RevokeRefreshToken
Content-Type: application/json

{
  "token" : "1DpGMbknsDRYN8ogRA4z8K/bpq3n9WpwUZinm4XGrcQ="
}
### Kullanıcıya rol atama (Manager rolü)
POST http://localhost:5294/api/User/AssignRole/afaruk59/Manager

### Kullanıcıya rol atama (Admin rolü)  
POST http://localhost:5294/api/User/AssignRole/afaruk59/Admin