GET http://localhost:5294/api/User
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3YTEzNjEzLTY2OGMtNGU3Ni1hZDJiLTk2MGRkNzNlNjZkYSIsImVtYWlsIjoiYWZhcnVrNTlAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImFmYXJ1azU5IiwianRpIjoiOTg0MzhkZGItOWM5Yy00ZWMxLWEzZjAtNzcyOTM5MTJjMzkyIiwiYXVkIjpbInd3dy5hdXRoc2VydmVyLmNvbSIsInd3dy5taW5pYXBpMS5jb20iLCJ3d3cubWluaWFwaTIuY29tIl0sIm5iZiI6MTc1NzA3NjU1NSwiZXhwIjoxNzU3MDc2ODU1LCJpc3MiOiJ3d3cuYXV0aHNlcnZlci5jb20ifQ.YsPpBkwmCU4LyPcDOlWq8n9k82Jr8np6wHJUUX5eHHg

### Token olustur
POST http://localhost:5294/api/Auth/CreateToken
   Content-Type: application/json

{
  "email": "afaruk59@gmail.com",
  "password": "Afaruk59**"
}
### kullanıcı olustur
POST http://localhost:5294/api/User
   Content-Type: application/json

{
  "userName": "afaruk59",
  "email": "afaruk59@gmail.com",
  "password": "Afaruk59**"
}
### Refresh ile token yenileme
POST http://localhost:5294/api/Auth/CreateTokenByRefreshToken
   Content-Type: application/json

{
  "token" : "ZpA6XhzNuGOnza3h/ak2c13i29L1XHLM5XOZtXKqKr4="
}
### Refresh Token geri alma
POST http://localhost:5294/api/Auth/RevokeRefreshToken
   Content-Type: application/json

{
  "token" : "1uRv7YjLToec3+1VwYmqZaHI29o9YSNaPzeWMflmLBg="
}
### urun cekme
GET http://localhost:5294/api/product
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3YTEzNjEzLTY2OGMtNGU3Ni1hZDJiLTk2MGRkNzNlNjZkYSIsImVtYWlsIjoiYWZhcnVrNTlAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImFmYXJ1azU5IiwianRpIjoiNzk4NTU0MGItYWM5Mi00N2MyLWIyNzMtOTI2MzIyYjc0NTg4IiwiYXVkIjpbInd3dy5hdXRoc2VydmVyLmNvbSIsInd3dy5taW5pYXBpMS5jb20iLCJ3d3cubWluaWFwaTIuY29tIl0sIm5iZiI6MTc1NzA3Njk4OSwiZXhwIjoxNzU3MDc3Mjg5LCJpc3MiOiJ3d3cuYXV0aHNlcnZlci5jb20ifQ.fkzZ1cMUHfhr0SFequGOPNHu1YPNBbISkxDZbbTyEPg
### urun ekleme
POST http://localhost:5294/api/product
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3YTEzNjEzLTY2OGMtNGU3Ni1hZDJiLTk2MGRkNzNlNjZkYSIsImVtYWlsIjoiYWZhcnVrNTlAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImFmYXJ1azU5IiwianRpIjoiNzk4NTU0MGItYWM5Mi00N2MyLWIyNzMtOTI2MzIyYjc0NTg4IiwiYXVkIjpbInd3dy5hdXRoc2VydmVyLmNvbSIsInd3dy5taW5pYXBpMS5jb20iLCJ3d3cubWluaWFwaTIuY29tIl0sIm5iZiI6MTc1NzA3Njk4OSwiZXhwIjoxNzU3MDc3Mjg5LCJpc3MiOiJ3d3cuYXV0aHNlcnZlci5jb20ifQ.fkzZ1cMUHfhr0SFequGOPNHu1YPNBbISkxDZbbTyEPg
Content-Type: application/json

{
  "id": 0,
  "name": "string",
  "price": 0,
  "userId": "a7a13613-668c-4e76-ad2b-960dd73e66da"
}
### urun guncelleme
PUT http://localhost:5294/api/product
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3YTEzNjEzLTY2OGMtNGU3Ni1hZDJiLTk2MGRkNzNlNjZkYSIsImVtYWlsIjoiYWZhcnVrNTlAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImFmYXJ1azU5IiwianRpIjoiNzk4NTU0MGItYWM5Mi00N2MyLWIyNzMtOTI2MzIyYjc0NTg4IiwiYXVkIjpbInd3dy5hdXRoc2VydmVyLmNvbSIsInd3dy5taW5pYXBpMS5jb20iLCJ3d3cubWluaWFwaTIuY29tIl0sIm5iZiI6MTc1NzA3Njk4OSwiZXhwIjoxNzU3MDc3Mjg5LCJpc3MiOiJ3d3cuYXV0aHNlcnZlci5jb20ifQ.fkzZ1cMUHfhr0SFequGOPNHu1YPNBbISkxDZbbTyEPg
Content-Type: application/json

{
  "id": 1,
  "name": "Urun 5",
  "price": 100,
  "userId": "a7a13613-668c-4e76-ad2b-960dd73e66da"
}
### urun silme
DELETE http://localhost:5294/api/product/1
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImE3YTEzNjEzLTY2OGMtNGU3Ni1hZDJiLTk2MGRkNzNlNjZkYSIsImVtYWlsIjoiYWZhcnVrNTlAZ21haWwuY29tIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImFmYXJ1azU5IiwianRpIjoiNzk4NTU0MGItYWM5Mi00N2MyLWIyNzMtOTI2MzIyYjc0NTg4IiwiYXVkIjpbInd3dy5hdXRoc2VydmVyLmNvbSIsInd3dy5taW5pYXBpMS5jb20iLCJ3d3cubWluaWFwaTIuY29tIl0sIm5iZiI6MTc1NzA3Njk4OSwiZXhwIjoxNzU3MDc3Mjg5LCJpc3MiOiJ3d3cuYXV0aHNlcnZlci5jb20ifQ.fkzZ1cMUHfhr0SFequGOPNHu1YPNBbISkxDZbbTyEPg

### client ile user olmadan token alma
POST http://localhost:5294/api/Auth/CreateTokenByClient
Content-Type: application/json

{
  "clientId": "SpaApp",
  "clientSecret": "secret"
}
### userrole
POST http://localhost:5294/api/User/CreateUserRoles/CreateUserRoles/afaruk59